theme: jekyll-theme-minimal
title: Improving software quality together
description: Literature review on coding practices in bioinformatics and ways to improve them
logo:
author: Katalin Ferenc, Ieva Rauluseviciute, Ladislav Hovan, Vipin Kumar, Marieke L. Kuijjer and Anthony Mathelier
show_downloads: true
google_analytics: